name: CI Pipeline

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore CalculatorSolution.sln

      - name: Build solution
        run: dotnet build CalculatorSolution.sln --configuration Release

      - name: Run tests
        run: dotnet test CalculatorSolution.sln --logger "trx;LogFileName=test_results.trx"

  analysis:
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Code Review Check for develop
        uses: actions/github-script@v6
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
              const pr = context.payload.pull_request;

              if (!pr) {
                core.setFailed("Це не Pull Request");
                return;
              }

              // Дозволяємо автору PR автоматично пройти перевірку
              if (pr.user.login === context.actor) {
                console.log("Автор PR, пропускаємо рев’ю");
                return;
              }

              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);

              const { data: reviews } = await octokit.rest.pulls.listReviews({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number
              });

              const approved = reviews.some(r => r.state === 'APPROVED');

              if (!approved) {
                core.setFailed("Код-рев’ю не схвалено");
              } else {
                console.log("Є схвалене рев’ю");
              }